#!/usr/bin/env python

import sys
from dataclasses import dataclass


@dataclass
class CommitMsg:
    commit_editmsg: str

    def convert(self) -> None:
        """Commitメッセージを変換する"""

        with open(self.commit_editmsg, "r+", encoding="utf-8") as f:
            commit_msg = f.read().strip()
            prefix, msg = commit_msg.split("/", 1)
            formatted_msg = self._convert_msg(prefix, msg)
            f.seek(0)
            f.write(formatted_msg)
            f.truncate()

    def _convert_msg(self, prefix: str, msg: str) -> str:
        """変換後のコミットメッセージを返す

        Args:
            prefix (str): コミットメッセージのprefix
            msg (str): コミットメッセージ本体

        Returns:
            str: 変換後のコミットメッセージ

        Raises:
            対応するprefixではない場合は`SyntaxError`
        """
        match prefix:
            case "feat":
                emoji = ":sparkles:"
            case "add":
                emoji = ":tada:"
            case "delete":
                emoji = ":boom:"
            case "fix":
                emoji = ":bug:"
            case "wip":
                emoji = ":construction:"
            case _:
                raise SyntaxError("Commitメッセージに構文の誤りがあります")
        return f"{emoji} {prefix} {msg}"


def main():
    commit_editmsg = sys.argv[1]
    CommitMsg(commit_editmsg).convert()


if __name__ == "__main__":
    main()
